name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose environment'
        required: true
        default: 'staging'
jobs:
  setup-local-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@develop
        with:
          name: Xela96/personal-website
          ref: refs/heads/release

  setup_node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: 16

  install_npm_latest:
    runs-on: ubuntu-latest
    steps:
      - run: npm i -g npm@latest

  install_dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: bahmutov/npm-install@v1

  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      env:
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
