name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose environment'
        required: true
        default: 'production'
        type: choice
        options:
          - local
          - production
      test_type:
        description: 'Choose test type'
        required: false
        default: "none"
        type: choice
        options:
          - none
          - smoke
          - functional
          - regression
          - search
          - filter
jobs:
  test-site:
    env:
      environment: ${{ github.event.inputs.environment }}
      TEST_TYPE: ${{ github.event.inputs.test_type }}

    runs-on: ubuntu-latest
    steps:
      # --- Checkout repos ---
      - name: Checkout test repo
        uses: actions/checkout@v3

      - name: Checkout personal website repo
        uses: actions/checkout@v3
        with:
          repository: Xela96/personal-website
          ref: develop
          path: personal-website

      # --- Setup Node ---
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16

      # --- Install npm latest ---
      - name: Upgrade npm
        run: npm install npm@latest

      # --- Install dependencies for Playwright tests ---
      - name: Install test dependencies
        uses: bahmutov/npm-install@v1
      

      
      # --- Setup and run Flask site ---
      - name: Install Python deps
        run: pip install -r personal-website/requirements.txt


      # --- File check ---
      - name: List files in current directory
        run: ls -la ./personal-website
        if: ${{ env.environment == 'local' }}

      - name: Run Flask app
        if: ${{ env.environment == 'local' }}
        run: |
          cd personal-website
          export FLASK_ENV=development
          flask run --host=0.0.0.0 --port=5000 &
          sleep 5
          curl -s http://127.0.0.1:5000/ || true
        shell: bash

      - name: Run Flask in background and log
        if: ${{ env.ENVIRONMENT == 'local' }}
        run: |
          cd personal-website
          export FLASK_ENV=development
          flask run --host=0.0.0.0 --port=5000 > flask.log 2>&1 &
          sleep 5
          cat flask.log

      # --- Setup URL to run tests on ---
      - name: Set TEST_URL based on environment
        run: |
          if [ "${environment}" = "production" ]; then
            echo "TEST_URL=https://dohertyalex.cc/" >> $GITHUB_ENV
          else
            echo "TEST_URL=http://127.0.0.1:5000" >> $GITHUB_ENV
          fi
      - name: Print TEST_URL
        run: echo "TEST_URL is $TEST_URL"
      
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps


      # --- Server check ---
      - name: Check if site is up
        run: curl -v http://127.0.0.1:5000/ || exit 1
        if: ${{ env.environment == 'local' }}

      # --- Run Playwright tests ---
      - name: Run Playwright tests with no tag
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}

        if : ${{ env.TEST_TYPE == 'none' }}
        run: npx playwright test
        working-directory: .

      # --- Run Playwright tests with a test tag ---
      - name: Run Playwright tests with tag
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
          TEST_TYPE: ${{ env.TEST_TYPE }}
          TEST_URL: ${{ env.TEST_URL }}
        if: ${{ env.TEST_TYPE == 'smoke' || env.TEST_TYPE == 'functional' || env.TEST_TYPE == 'regression' || env.TEST_TYPE == 'search' || env.TEST_TYPE == 'filter' }}
        run: npx playwright test --grep=@${{ env.TEST_TYPE }}
        working-directory: .

      # --- Upload Playwright test report ---
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30